export const TIER_LIMITS = {
  STARTER: {
    name: "Starter",
    labelBadge: "STARTER • PERINTIS",
    originalPrice: 350000,
    price: 250000,
    discountBadge: "HEMAT 28%",
    tagline: "Langkah Awal Konter Manual Jadi Katalog Online",
    period: "/ bulan",
    maxActiveProducts: 15,
    maxAdmins: 1,
    allowedTemplates: 1,
    templateChangeCooldownDays: 0, // Bebas
    hasWatermark: false,
    customDomain: false,
    canCustomProfile: false,
    allowCustomerReviews: false,
    maxReviews: 0,
    description: "Solusi hemat untuk toko HP pemula / konter personal yang ingin katalog online rapi.",
    qrKit: {
      allowGoogleReview: false,
      allowHdDownload: false,
      showWatermarkPlatform: true, // label footer: "Powered by gadgetbdg.com"
      allowedFormats: ["compact-mono"] as const,
    },
  },
  PRO: {
    name: "Pro",
    labelBadge: "PRO • BISNIS MANDIRI",
    originalPrice: 850000,
    price: 600000,
    discountBadge: "HEMAT 30%",
    popularBadge: "PALING POPULER",
    tagline: "Solusi Lengkap Toko Berkembang: Bebas Curi Foto",
    period: "/ bulan",
    maxActiveProducts: 30,
    maxAdmins: 3,
    allowedTemplates: 3,
    templateChangeCooldownDays: 30, // 1x per 30 hari
    hasWatermark: true,
    customDomain: true,
    canCustomProfile: true,
    allowCustomerReviews: true,
    maxReviews: 25,
    description: "Untuk konter HP aktif BEC / Bandung yang ingin scale-up penjualan & branding profesional.",
    qrKit: {
      allowGoogleReview: true,
      allowHdDownload: true,
      showWatermarkPlatform: false,
      allowedFormats: ["compact-mono", "acrylic-stand", "tent-card"] as const,
    },
  },
  ADVANCE: {
    name: "Advance",
    labelBadge: "ADVANCE • KELAS SULTAN",
    originalPrice: 1500000,
    price: 1000000,
    discountBadge: "HEMAT 33%",
    popularBadge: "EKSKLUSIF",
    tagline: "Ekosistem Tanpa Batas untuk Jaringan Cabang",
    period: "/ bulan",
    maxActiveProducts: Infinity,
    maxAdmins: 5,
    allowedTemplates: 6,
    templateChangeCooldownDays: 0, // Bebas ganti kapan saja
    hasWatermark: true,
    customDomain: true,
    canCustomProfile: true,
    allowCustomerReviews: true,
    maxReviews: Infinity,
    description: "Kapasitas tanpa batas untuk juragan HP second dengan perputaran stok masif & multi-cabang.",
    qrKit: {
      allowGoogleReview: true,
      allowHdDownload: true,
      showWatermarkPlatform: false,
      allowedFormats: ["compact-mono", "acrylic-stand", "tent-card", "gold-luxury", "badge-custom"] as const,
    },
  },
} as const;

export type TierType = keyof typeof TIER_LIMITS;
