export const TIER_LIMITS = {
  STARTER: {
    name: "Starter",
    labelBadge: "STARTER • PERINTIS",
    originalPrice: 500000,
    price: 300000,
    discountBadge: "HEMAT 40%",
    tagline: "Langkah Awal Konter Manual Jadi Katalog Online",
    period: "/ bulan",
    productLimit: 50,
    maxActiveProducts: 50,
    maxAdmins: 1,
    allowedTemplates: 2,
    availableTemplatesCount: 2,
    templateChangeCooldownDays: -1, // Hanya 1x saat pendaftaran
    templateChangeRule: "Hanya 1x saat pendaftaran",
    hasWatermark: false,
    hasQrWebsite: true,
    hasQrGoogleReview: true,
    reports: "Laporan klik WhatsApp saja",
    storyFeature: "Tombol share link di halaman web produk",
    customDomain: false,
    canCustomProfile: false,
    allowCustomerReviews: false,
    maxReviews: 0,
    description: "Solusi hemat untuk toko HP pemula / konter personal yang ingin katalog online rapi.",
    qrKit: {
      allowGoogleReview: true,
      allowHdDownload: true,
      showWatermarkPlatform: true, // label footer: "Powered by gadgetbdg.com"
      allowedFormats: ["compact-mono", "acrylic-stand", "tent-card"] as const,
    },
  },
  PRO: {
    name: "Pro",
    labelBadge: "PRO • BISNIS MANDIRI",
    originalPrice: 1000000,
    price: 600000,
    discountBadge: "HEMAT 40%",
    popularBadge: "PALING POPULER",
    tagline: "Solusi Lengkap Toko Berkembang: Bebas Curi Foto",
    period: "/ bulan",
    productLimit: null,
    maxActiveProducts: Infinity,
    maxAdmins: 3,
    allowedTemplates: 4,
    availableTemplatesCount: 4,
    templateChangeCooldownDays: 30, // Tiap 30 hari
    templateCooldownDays: 30,
    templateChangeRule: "Ganti template tiap 30 hari",
    hasWatermark: true,
    hasQrWebsite: true,
    hasQrGoogleReview: true,
    reports: "Rekap omset SOLD & Leaderboard produk diminati",
    storyFeature: "Auto-Generate Story 9:16 HD & Preset Promo",
    customDomain: true,
    canCustomProfile: true,
    allowCustomerReviews: true,
    maxReviews: 25,
    description: "Untuk konter HP aktif BEC / Bandung yang ingin scale-up penjualan & branding profesional.",
    qrKit: {
      allowGoogleReview: true,
      allowHdDownload: true,
      showWatermarkPlatform: false,
      allowedFormats: ["compact-mono", "acrylic-stand", "tent-card"] as const,
    },
  },
  ADVANCE: {
    name: "Advance",
    labelBadge: "ADVANCE • KELAS SULTAN",
    archiveBadge: "ARCHIVED",
    isArchived: true,
    originalPrice: 1500000,
    price: 1000000,
    discountBadge: "HEMAT 33%",
    popularBadge: "EKSKLUSIF",
    tagline: "Ekosistem Tanpa Batas untuk Jaringan Cabang (Archived)",
    period: "/ bulan",
    productLimit: null,
    maxActiveProducts: Infinity,
    maxAdmins: 5, // per cabang
    allowedTemplates: 6,
    availableTemplatesCount: 6,
    templateChangeCooldownDays: 0, // Kapan saja
    templateCooldownDays: 0,
    templateChangeRule: "Bebas ganti template kapan saja",
    hasWatermark: true,
    hasQrWebsite: true,
    hasQrGoogleReview: true,
    reports: "Laporan omset lengkap per cabang",
    storyFeature: "Auto-Generate Story 9:16 + Format Multi-Cabang",
    customDomain: true,
    canCustomProfile: true,
    allowCustomerReviews: true,
    maxReviews: Infinity,
    description: "Kapasitas tanpa batas untuk juragan HP second dengan perputaran stok masif & multi-cabang.",
    qrKit: {
      allowGoogleReview: true,
      allowHdDownload: true,
      showWatermarkPlatform: false,
      allowedFormats: ["compact-mono", "acrylic-stand", "tent-card", "gold-luxury", "badge-custom"] as const,
    },
  },
} as const;

export type TierType = keyof typeof TIER_LIMITS;
