export interface TemplateThemeConfig {
  id: string;
  name: string;
  category: "Starter" | "Pro" | "Advance";
  tierRequired: "STARTER" | "PRO" | "ADVANCE";
  description: string;
  badge?: string;
  colors: {
    isDark: boolean;
    bgMain: string;
    bgContainer: string;
    borderContainer: string;
    textPrimary: string;
    textSecondary: string;
    accent: string;
    accentHover: string;
    accentText: string;
    badgeVerifiedBg: string;
    badgeVerifiedText: string;
    badgeVerifiedBorder: string;
    cardBg: string;
    cardBorder: string;
    cardHoverBorder: string;
    headerBg: string;
    bottomNavBg: string;
    bottomNavBorder: string;
    bottomNavActive: string;
    bottomNavInactive: string;
    priceText: string;
    heroGradient: string;
    heroBorder: string;
  };
}

export const TEMPLATE_REGISTRY: Record<string, TemplateThemeConfig> = {
  // ==========================================
  // STARTER TIER (2 Template)
  // ==========================================
  "minimal-clean": {
    id: "minimal-clean",
    name: "Minimal Clean",
    category: "Starter",
    tierRequired: "STARTER",
    description: "Desain cerah, elegan, putih bersih. Sangat cocok untuk toko spesialis iPhone resmi iBox & Android flagship.",
    badge: "Populer Starter",
    colors: {
      isDark: false,
      bgMain: "bg-neutral-100",
      bgContainer: "bg-white",
      borderContainer: "border-neutral-200",
      textPrimary: "text-neutral-900",
      textSecondary: "text-neutral-500",
      accent: "bg-blue-600",
      accentHover: "hover:bg-blue-700",
      accentText: "text-blue-600",
      badgeVerifiedBg: "bg-blue-50",
      badgeVerifiedText: "text-blue-700",
      badgeVerifiedBorder: "border-blue-200",
      cardBg: "bg-white",
      cardBorder: "border-neutral-200",
      cardHoverBorder: "hover:border-blue-300",
      headerBg: "bg-white/90 border-neutral-200 text-neutral-900",
      bottomNavBg: "bg-white/95 border-neutral-200",
      bottomNavBorder: "border-neutral-200",
      bottomNavActive: "text-blue-600 font-bold",
      bottomNavInactive: "text-neutral-500 hover:text-neutral-800",
      priceText: "text-blue-700",
      heroGradient: "bg-gradient-to-br from-blue-600 via-indigo-600 to-blue-700 text-white",
      heroBorder: "border-blue-500",
    },
  },
  "dark-gaming": {
    id: "dark-gaming",
    name: "Dark Gaming Cyber",
    category: "Starter",
    tierRequired: "STARTER",
    description: "Nuansa hitam futuristik dengan aksen neon hijau emerald. Populer untuk HP gaming ROG, iQOO, dan POCO.",
    badge: "High FPS",
    colors: {
      isDark: true,
      bgMain: "bg-slate-950",
      bgContainer: "bg-slate-900",
      borderContainer: "border-slate-800",
      textPrimary: "text-slate-100",
      textSecondary: "text-slate-400",
      accent: "bg-emerald-500",
      accentHover: "hover:bg-emerald-400",
      accentText: "text-emerald-400",
      badgeVerifiedBg: "bg-emerald-950",
      badgeVerifiedText: "text-emerald-300",
      badgeVerifiedBorder: "border-emerald-800/80",
      cardBg: "bg-slate-950/70",
      cardBorder: "border-slate-800",
      cardHoverBorder: "hover:border-emerald-500/40",
      headerBg: "bg-slate-900/90 border-slate-800 text-white",
      bottomNavBg: "bg-slate-900/95 border-slate-800",
      bottomNavBorder: "border-slate-800",
      bottomNavActive: "text-emerald-400 font-bold",
      bottomNavInactive: "text-slate-400 hover:text-slate-200",
      priceText: "text-emerald-400 font-mono",
      heroGradient: "bg-gradient-to-br from-slate-900 via-emerald-950/60 to-slate-950 text-white",
      heroBorder: "border-emerald-500/30",
    },
  },

  // ==========================================
  // PRO TIER (8 Template Baru, total 10)
  // ==========================================
  "flagship-gold": {
    id: "flagship-gold",
    name: "Flagship Luxury Gold",
    category: "Pro",
    tierRequired: "PRO",
    description: "Nuansa mewah hitam obsidian & aksen emas glamor untuk konter spesialis iPhone Pro & Samsung Fold/Flip.",
    badge: "Mewah & Eksklusif",
    colors: {
      isDark: true,
      bgMain: "bg-stone-950",
      bgContainer: "bg-stone-900",
      borderContainer: "border-amber-900/40",
      textPrimary: "text-amber-50",
      textSecondary: "text-amber-200/60",
      accent: "bg-amber-500",
      accentHover: "hover:bg-amber-400",
      accentText: "text-amber-400",
      badgeVerifiedBg: "bg-amber-950",
      badgeVerifiedText: "text-amber-300",
      badgeVerifiedBorder: "border-amber-700/60",
      cardBg: "bg-stone-950/80",
      cardBorder: "border-amber-900/30",
      cardHoverBorder: "hover:border-amber-500/50",
      headerBg: "bg-stone-900/90 border-amber-950 text-amber-100",
      bottomNavBg: "bg-stone-900/95 border-amber-950",
      bottomNavBorder: "border-amber-950",
      bottomNavActive: "text-amber-400 font-bold",
      bottomNavInactive: "text-stone-400 hover:text-amber-200",
      priceText: "text-amber-300 font-mono",
      heroGradient: "bg-gradient-to-br from-stone-900 via-amber-950 to-stone-950 text-amber-50",
      heroBorder: "border-amber-600/30",
    },
  },
  "cyber-blue": {
    id: "cyber-blue",
    name: "Cyberpunk Electric Cyan",
    category: "Pro",
    tierRequired: "PRO",
    description: "Latar dark futuristik dengan glow cyan neon elektrik berkecepatan tinggi.",
    badge: "Glow Cyan",
    colors: {
      isDark: true,
      bgMain: "bg-zinc-950",
      bgContainer: "bg-zinc-900",
      borderContainer: "border-cyan-900/40",
      textPrimary: "text-cyan-50",
      textSecondary: "text-cyan-300/60",
      accent: "bg-cyan-500",
      accentHover: "hover:bg-cyan-400",
      accentText: "text-cyan-400",
      badgeVerifiedBg: "bg-cyan-950",
      badgeVerifiedText: "text-cyan-300",
      badgeVerifiedBorder: "border-cyan-700/60",
      cardBg: "bg-zinc-950/80",
      cardBorder: "border-cyan-900/30",
      cardHoverBorder: "hover:border-cyan-500/50",
      headerBg: "bg-zinc-900/90 border-cyan-950 text-cyan-50",
      bottomNavBg: "bg-zinc-900/95 border-cyan-950",
      bottomNavBorder: "border-cyan-950",
      bottomNavActive: "text-cyan-400 font-bold",
      bottomNavInactive: "text-zinc-400 hover:text-cyan-200",
      priceText: "text-cyan-400 font-mono",
      heroGradient: "bg-gradient-to-br from-zinc-900 via-cyan-950 to-zinc-950 text-cyan-50",
      heroBorder: "border-cyan-500/40",
    },
  },
  "tokyo-street": {
    id: "tokyo-street",
    name: "Tokyo Streetwear Warm",
    category: "Pro",
    tierRequired: "PRO",
    description: "Latar warm stone krem/off-white dengan tipografi urban bold & aksen terracotta modern.",
    badge: "Urban Aesthetic",
    colors: {
      isDark: false,
      bgMain: "bg-[#f5f2eb]",
      bgContainer: "bg-[#fcfbf7]",
      borderContainer: "border-[#e6dfd1]",
      textPrimary: "text-[#24211d]",
      textSecondary: "text-[#7a7469]",
      accent: "bg-[#c25e38]",
      accentHover: "hover:bg-[#a64e2c]",
      accentText: "text-[#c25e38]",
      badgeVerifiedBg: "bg-[#fbebe4]",
      badgeVerifiedText: "text-[#943d1a]",
      badgeVerifiedBorder: "border-[#f3cebe]",
      cardBg: "bg-white",
      cardBorder: "border-[#e6dfd1]",
      cardHoverBorder: "hover:border-[#c25e38]/50",
      headerBg: "bg-[#fcfbf7]/90 border-[#e6dfd1] text-[#24211d]",
      bottomNavBg: "bg-[#fcfbf7]/95 border-[#e6dfd1]",
      bottomNavBorder: "border-[#e6dfd1]",
      bottomNavActive: "text-[#c25e38] font-bold",
      bottomNavInactive: "text-[#7a7469] hover:text-[#24211d]",
      priceText: "text-[#c25e38] font-bold",
      heroGradient: "bg-gradient-to-br from-[#c25e38] via-[#d47854] to-[#a64e2c] text-white",
      heroBorder: "border-[#c25e38]",
    },
  },
  "sunset-vibes": {
    id: "sunset-vibes",
    name: "Sunset Vibrant Glow",
    category: "Pro",
    tierRequired: "PRO",
    description: "Kombinasi warna senja hangat jingga dan fuchsia rose yang enerjik & catchy.",
    badge: "Eye-Catching",
    colors: {
      isDark: false,
      bgMain: "bg-rose-50/50",
      bgContainer: "bg-white",
      borderContainer: "border-rose-100",
      textPrimary: "text-slate-900",
      textSecondary: "text-slate-500",
      accent: "bg-rose-500",
      accentHover: "hover:bg-rose-600",
      accentText: "text-rose-600",
      badgeVerifiedBg: "bg-rose-50",
      badgeVerifiedText: "text-rose-700",
      badgeVerifiedBorder: "border-rose-200",
      cardBg: "bg-white",
      cardBorder: "border-rose-100",
      cardHoverBorder: "hover:border-rose-300",
      headerBg: "bg-white/90 border-rose-100 text-slate-900",
      bottomNavBg: "bg-white/95 border-rose-100",
      bottomNavBorder: "border-rose-100",
      bottomNavActive: "text-rose-600 font-bold",
      bottomNavInactive: "text-slate-400 hover:text-slate-700",
      priceText: "text-rose-600 font-bold",
      heroGradient: "bg-gradient-to-br from-amber-500 via-rose-500 to-pink-600 text-white",
      heroBorder: "border-rose-400",
    },
  },
  "monochrome-bold": {
    id: "monochrome-bold",
    name: "Monochrome High Contrast",
    category: "Pro",
    tierRequired: "PRO",
    description: "Hitam pekat dan putih bersih kontras tinggi bergaya editorial minimalis tanpa distraksi.",
    badge: "Minimalis Tajam",
    colors: {
      isDark: false,
      bgMain: "bg-neutral-100",
      bgContainer: "bg-white",
      borderContainer: "border-neutral-300",
      textPrimary: "text-black",
      textSecondary: "text-neutral-600",
      accent: "bg-black",
      accentHover: "hover:bg-neutral-800",
      accentText: "text-black",
      badgeVerifiedBg: "bg-neutral-100",
      badgeVerifiedText: "text-black",
      badgeVerifiedBorder: "border-neutral-300",
      cardBg: "bg-white",
      cardBorder: "border-neutral-300",
      cardHoverBorder: "hover:border-black",
      headerBg: "bg-white/90 border-neutral-300 text-black",
      bottomNavBg: "bg-white/95 border-neutral-300",
      bottomNavBorder: "border-neutral-300",
      bottomNavActive: "text-black font-extrabold",
      bottomNavInactive: "text-neutral-400 hover:text-black",
      priceText: "text-black font-extrabold font-mono",
      heroGradient: "bg-gradient-to-br from-black via-neutral-900 to-neutral-800 text-white",
      heroBorder: "border-neutral-700",
    },
  },
  "emerald-pro": {
    id: "emerald-pro",
    name: "Emerald Merchant Elegance",
    category: "Pro",
    tierRequired: "PRO",
    description: "Warna hijau botol mewah ala toko perhiasan dengan aksen sage mint bersih.",
    badge: "Green Luxury",
    colors: {
      isDark: false,
      bgMain: "bg-emerald-50/40",
      bgContainer: "bg-white",
      borderContainer: "border-emerald-100",
      textPrimary: "text-emerald-950",
      textSecondary: "text-emerald-800/70",
      accent: "bg-emerald-700",
      accentHover: "hover:bg-emerald-800",
      accentText: "text-emerald-700",
      badgeVerifiedBg: "bg-emerald-50",
      badgeVerifiedText: "text-emerald-800",
      badgeVerifiedBorder: "border-emerald-200",
      cardBg: "bg-white",
      cardBorder: "border-emerald-100",
      cardHoverBorder: "hover:border-emerald-300",
      headerBg: "bg-white/90 border-emerald-100 text-emerald-950",
      bottomNavBg: "bg-white/95 border-emerald-100",
      bottomNavBorder: "border-emerald-100",
      bottomNavActive: "text-emerald-700 font-bold",
      bottomNavInactive: "text-slate-400 hover:text-emerald-800",
      priceText: "text-emerald-700 font-bold",
      heroGradient: "bg-gradient-to-br from-emerald-800 via-teal-800 to-emerald-900 text-white",
      heroBorder: "border-emerald-700",
    },
  },
  "nordic-frost": {
    id: "nordic-frost",
    name: "Nordic Frost Ice Blue",
    category: "Pro",
    tierRequired: "PRO",
    description: "Nuansa biru es Skandinavia yang tenang, sejuk, dan memberikan rasa aman pembeli.",
    badge: "Clean Frost",
    colors: {
      isDark: false,
      bgMain: "bg-sky-50/60",
      bgContainer: "bg-white",
      borderContainer: "border-sky-100",
      textPrimary: "text-slate-800",
      textSecondary: "text-slate-500",
      accent: "bg-sky-600",
      accentHover: "hover:bg-sky-700",
      accentText: "text-sky-600",
      badgeVerifiedBg: "bg-sky-50",
      badgeVerifiedText: "text-sky-800",
      badgeVerifiedBorder: "border-sky-200",
      cardBg: "bg-white",
      cardBorder: "border-sky-100",
      cardHoverBorder: "hover:border-sky-300",
      headerBg: "bg-white/90 border-sky-100 text-slate-800",
      bottomNavBg: "bg-white/95 border-sky-100",
      bottomNavBorder: "border-sky-100",
      bottomNavActive: "text-sky-600 font-bold",
      bottomNavInactive: "text-slate-400 hover:text-slate-700",
      priceText: "text-sky-700 font-bold",
      heroGradient: "bg-gradient-to-br from-sky-600 via-blue-600 to-indigo-700 text-white",
      heroBorder: "border-sky-400",
    },
  },
  "midnight-purple": {
    id: "midnight-purple",
    name: "Midnight Neon Purple",
    category: "Pro",
    tierRequired: "PRO",
    description: "Tema malam misterius dengan aksen ungu violet neon pekat yang estetik.",
    badge: "Violet Glow",
    colors: {
      isDark: true,
      bgMain: "bg-[#0b0614]",
      bgContainer: "bg-[#140b24]",
      borderContainer: "border-purple-950",
      textPrimary: "text-purple-50",
      textSecondary: "text-purple-300/60",
      accent: "bg-purple-600",
      accentHover: "hover:bg-purple-500",
      accentText: "text-purple-400",
      badgeVerifiedBg: "bg-purple-950",
      badgeVerifiedText: "text-purple-300",
      badgeVerifiedBorder: "border-purple-800/80",
      cardBg: "bg-[#140b24]/80",
      cardBorder: "border-purple-950",
      cardHoverBorder: "hover:border-purple-500/50",
      headerBg: "bg-[#140b24]/90 border-purple-950 text-purple-100",
      bottomNavBg: "bg-[#140b24]/95 border-purple-950",
      bottomNavBorder: "border-purple-950",
      bottomNavActive: "text-purple-400 font-bold",
      bottomNavInactive: "text-purple-400/60 hover:text-purple-200",
      priceText: "text-purple-300 font-mono",
      heroGradient: "bg-gradient-to-br from-[#1b0d33] via-[#2a1352] to-[#120724] text-purple-50",
      heroBorder: "border-purple-600/40",
    },
  },

  // ==========================================
  // ADVANCE TIER (+20 Preset Varian Ritel & Event Musiman, Total 30)
  // ==========================================
  "ramadhan-blessing": {
    id: "ramadhan-blessing",
    name: "Ramadhan & Lebaran Mubarak",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Tema khusus berkah Ramadhan & festival THR Lebaran dengan aksen hijau emerald & kaligrafi islami modern.",
    badge: "Event Musiman",
    colors: {
      isDark: false,
      bgMain: "bg-[#f0f7f3]",
      bgContainer: "bg-white",
      borderContainer: "border-emerald-200",
      textPrimary: "text-emerald-950",
      textSecondary: "text-emerald-700/80",
      accent: "bg-emerald-600",
      accentHover: "hover:bg-emerald-700",
      accentText: "text-emerald-600",
      badgeVerifiedBg: "bg-emerald-50",
      badgeVerifiedText: "text-emerald-800",
      badgeVerifiedBorder: "border-emerald-200",
      cardBg: "bg-white",
      cardBorder: "border-emerald-100",
      cardHoverBorder: "hover:border-emerald-400",
      headerBg: "bg-white/90 border-emerald-200 text-emerald-950",
      bottomNavBg: "bg-white/95 border-emerald-200",
      bottomNavBorder: "border-emerald-200",
      bottomNavActive: "text-emerald-600 font-bold",
      bottomNavInactive: "text-emerald-700/60 hover:text-emerald-900",
      priceText: "text-emerald-700 font-bold",
      heroGradient: "bg-gradient-to-br from-emerald-700 via-teal-700 to-amber-600 text-white",
      heroBorder: "border-emerald-500",
    },
  },
  "flash-sale-red": {
    id: "flash-sale-red",
    name: "Flash Sale Countdown Red",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Merah agresif bersemangat untuk mendorong urgensi diskon kilat dan cuci gudang akhir pekan.",
    badge: "Diskon Cepat",
    colors: {
      isDark: false,
      bgMain: "bg-red-50/50",
      bgContainer: "bg-white",
      borderContainer: "border-red-200",
      textPrimary: "text-slate-900",
      textSecondary: "text-slate-500",
      accent: "bg-red-600",
      accentHover: "hover:bg-red-700",
      accentText: "text-red-600",
      badgeVerifiedBg: "bg-red-50",
      badgeVerifiedText: "text-red-700",
      badgeVerifiedBorder: "border-red-200",
      cardBg: "bg-white",
      cardBorder: "border-red-100",
      cardHoverBorder: "hover:border-red-400",
      headerBg: "bg-white/90 border-red-200 text-slate-900",
      bottomNavBg: "bg-white/95 border-red-200",
      bottomNavBorder: "border-red-200",
      bottomNavActive: "text-red-600 font-bold",
      bottomNavInactive: "text-slate-400 hover:text-slate-700",
      priceText: "text-red-600 font-black",
      heroGradient: "bg-gradient-to-br from-red-600 via-rose-600 to-amber-600 text-white",
      heroBorder: "border-red-500",
    },
  },
  "clearance-yellow": {
    id: "clearance-yellow",
    name: "Clearance Sale Yellow Tag",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Kuning terang dan hitam kontras untuk kampanye cuci gudang unit HP minus ringan atau harga grosir.",
    badge: "Cuci Gudang",
    colors: {
      isDark: false,
      bgMain: "bg-amber-50/60",
      bgContainer: "bg-white",
      borderContainer: "border-amber-200",
      textPrimary: "text-slate-950",
      textSecondary: "text-slate-600",
      accent: "bg-amber-500",
      accentHover: "hover:bg-amber-600",
      accentText: "text-amber-600",
      badgeVerifiedBg: "bg-amber-100",
      badgeVerifiedText: "text-amber-900",
      badgeVerifiedBorder: "border-amber-300",
      cardBg: "bg-white",
      cardBorder: "border-amber-200",
      cardHoverBorder: "hover:border-amber-500",
      headerBg: "bg-white/90 border-amber-200 text-slate-950",
      bottomNavBg: "bg-white/95 border-amber-200",
      bottomNavBorder: "border-amber-200",
      bottomNavActive: "text-amber-600 font-bold",
      bottomNavInactive: "text-slate-400 hover:text-slate-700",
      priceText: "text-amber-600 font-black",
      heroGradient: "bg-gradient-to-br from-amber-500 via-orange-500 to-yellow-600 text-slate-950",
      heroBorder: "border-amber-400",
    },
  },
  "new-year-celebration": {
    id: "new-year-celebration",
    name: "New Year Sparkle Gold",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Festival pergantian tahun dengan kilau kembang api emas dan warna malam glamor.",
    badge: "Tahun Baru",
    colors: {
      isDark: true,
      bgMain: "bg-[#0d0d12]",
      bgContainer: "bg-[#181822]",
      borderContainer: "border-amber-500/20",
      textPrimary: "text-slate-100",
      textSecondary: "text-slate-400",
      accent: "bg-amber-400",
      accentHover: "hover:bg-amber-300",
      accentText: "text-amber-400",
      badgeVerifiedBg: "bg-amber-950",
      badgeVerifiedText: "text-amber-300",
      badgeVerifiedBorder: "border-amber-700/60",
      cardBg: "bg-[#181822]/80",
      cardBorder: "border-amber-500/20",
      cardHoverBorder: "hover:border-amber-400/50",
      headerBg: "bg-[#181822]/90 border-amber-500/20 text-white",
      bottomNavBg: "bg-[#181822]/95 border-amber-500/20",
      bottomNavBorder: "border-amber-500/20",
      bottomNavActive: "text-amber-400 font-bold",
      bottomNavInactive: "text-slate-400 hover:text-slate-200",
      priceText: "text-amber-400 font-mono",
      heroGradient: "bg-gradient-to-br from-[#181822] via-[#2d2417] to-amber-950 text-white",
      heroBorder: "border-amber-400/40",
    },
  },
  "harbolnas-1212": {
    id: "harbolnas-1212",
    name: "Harbolnas Mega Sale 12.12",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Aksen merah fuchsia khas festival belanja nasional Harbolnas untuk toko volume tinggi.",
    badge: "Mega Sale",
    colors: {
      isDark: false,
      bgMain: "bg-pink-50/50",
      bgContainer: "bg-white",
      borderContainer: "border-pink-200",
      textPrimary: "text-slate-900",
      textSecondary: "text-slate-500",
      accent: "bg-pink-600",
      accentHover: "hover:bg-pink-700",
      accentText: "text-pink-600",
      badgeVerifiedBg: "bg-pink-50",
      badgeVerifiedText: "text-pink-700",
      badgeVerifiedBorder: "border-pink-200",
      cardBg: "bg-white",
      cardBorder: "border-pink-100",
      cardHoverBorder: "hover:border-pink-400",
      headerBg: "bg-white/90 border-pink-200 text-slate-900",
      bottomNavBg: "bg-white/95 border-pink-200",
      bottomNavBorder: "border-pink-200",
      bottomNavActive: "text-pink-600 font-bold",
      bottomNavInactive: "text-slate-400 hover:text-slate-700",
      priceText: "text-pink-600 font-black",
      heroGradient: "bg-gradient-to-br from-pink-600 via-rose-600 to-indigo-700 text-white",
      heroBorder: "border-pink-400",
    },
  },
  "merdeka-indonesia": {
    id: "merdeka-indonesia",
    name: "Merdeka Semangat 45",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Tema patriotik Merah Putih menyambut promo 17 Agustus Hari Kemerdekaan RI.",
    badge: "17 Agustus",
    colors: {
      isDark: false,
      bgMain: "bg-neutral-100",
      bgContainer: "bg-white",
      borderContainer: "border-red-200",
      textPrimary: "text-slate-900",
      textSecondary: "text-slate-500",
      accent: "bg-red-700",
      accentHover: "hover:bg-red-800",
      accentText: "text-red-700",
      badgeVerifiedBg: "bg-red-50",
      badgeVerifiedText: "text-red-800",
      badgeVerifiedBorder: "border-red-300",
      cardBg: "bg-white",
      cardBorder: "border-neutral-200",
      cardHoverBorder: "hover:border-red-500",
      headerBg: "bg-white/90 border-red-200 text-slate-900",
      bottomNavBg: "bg-white/95 border-red-200",
      bottomNavBorder: "border-red-200",
      bottomNavActive: "text-red-700 font-bold",
      bottomNavInactive: "text-slate-400 hover:text-slate-700",
      priceText: "text-red-700 font-black",
      heroGradient: "bg-gradient-to-br from-red-600 via-red-700 to-rose-900 text-white",
      heroBorder: "border-red-500",
    },
  },
  "payday-gajian": {
    id: "payday-gajian",
    name: "Payday Super Promo Gajian",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Warna hijau toska cerah menyambut tanggal gajian tiap tanggal 25-30.",
    badge: "Promo Gajian",
    colors: {
      isDark: false,
      bgMain: "bg-teal-50/50",
      bgContainer: "bg-white",
      borderContainer: "border-teal-200",
      textPrimary: "text-slate-900",
      textSecondary: "text-slate-500",
      accent: "bg-teal-600",
      accentHover: "hover:bg-teal-700",
      accentText: "text-teal-600",
      badgeVerifiedBg: "bg-teal-50",
      badgeVerifiedText: "text-teal-800",
      badgeVerifiedBorder: "border-teal-200",
      cardBg: "bg-white",
      cardBorder: "border-teal-100",
      cardHoverBorder: "hover:border-teal-400",
      headerBg: "bg-white/90 border-teal-200 text-slate-900",
      bottomNavBg: "bg-white/95 border-teal-200",
      bottomNavBorder: "border-teal-200",
      bottomNavActive: "text-teal-600 font-bold",
      bottomNavInactive: "text-slate-400 hover:text-slate-700",
      priceText: "text-teal-700 font-black",
      heroGradient: "bg-gradient-to-br from-teal-600 via-emerald-600 to-cyan-700 text-white",
      heroBorder: "border-teal-400",
    },
  },
  "apple-titanium": {
    id: "apple-titanium",
    name: "Natural Titanium Pro",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Terinspirasi oleh warna Natural Titanium iPhone 15/16 Pro dengan tekstur brushed metal elegan.",
    badge: "Titanium Edition",
    colors: {
      isDark: false,
      bgMain: "bg-[#e8e7e3]",
      bgContainer: "bg-[#f5f4f0]",
      borderContainer: "border-[#d4d2cc]",
      textPrimary: "text-[#343330]",
      textSecondary: "text-[#6e6c66]",
      accent: "bg-[#54524c]",
      accentHover: "hover:bg-[#3c3a35]",
      accentText: "text-[#54524c]",
      badgeVerifiedBg: "bg-[#e3e1db]",
      badgeVerifiedText: "text-[#343330]",
      badgeVerifiedBorder: "border-[#c4c2bb]",
      cardBg: "bg-white",
      cardBorder: "border-[#dcd9d2]",
      cardHoverBorder: "hover:border-[#54524c]",
      headerBg: "bg-[#f5f4f0]/90 border-[#d4d2cc] text-[#343330]",
      bottomNavBg: "bg-[#f5f4f0]/95 border-[#d4d2cc]",
      bottomNavBorder: "border-[#d4d2cc]",
      bottomNavActive: "text-[#343330] font-extrabold",
      bottomNavInactive: "text-[#6e6c66] hover:text-[#343330]",
      priceText: "text-[#343330] font-bold font-mono",
      heroGradient: "bg-gradient-to-br from-[#54524c] via-[#6d6b63] to-[#3c3a35] text-[#f5f4f0]",
      heroBorder: "border-[#54524c]",
    },
  },
  "galaxy-ai-violet": {
    id: "galaxy-ai-violet",
    name: "Galaxy AI Titanium Violet",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Nuansa titanium violet flagship Galaxy S24 Ultra dengan aksen AI futuristik.",
    badge: "Flagship Galaxy",
    colors: {
      isDark: true,
      bgMain: "bg-[#0f0e1c]",
      bgContainer: "bg-[#18162e]",
      borderContainer: "border-indigo-950",
      textPrimary: "text-indigo-50",
      textSecondary: "text-indigo-300/60",
      accent: "bg-indigo-600",
      accentHover: "hover:bg-indigo-500",
      accentText: "text-indigo-400",
      badgeVerifiedBg: "bg-indigo-950",
      badgeVerifiedText: "text-indigo-300",
      badgeVerifiedBorder: "border-indigo-800/80",
      cardBg: "bg-[#18162e]/80",
      cardBorder: "border-indigo-950",
      cardHoverBorder: "hover:border-indigo-500/50",
      headerBg: "bg-[#18162e]/90 border-indigo-950 text-indigo-50",
      bottomNavBg: "bg-[#18162e]/95 border-indigo-950",
      bottomNavBorder: "border-indigo-950",
      bottomNavActive: "text-indigo-400 font-bold",
      bottomNavInactive: "text-indigo-400/60 hover:text-indigo-200",
      priceText: "text-indigo-300 font-mono",
      heroGradient: "bg-gradient-to-br from-[#1a1738] via-[#292459] to-[#120f26] text-white",
      heroBorder: "border-indigo-500/40",
    },
  },
  "forest-military": {
    id: "forest-military",
    name: "Tactical Forest Military",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Hijau army zaitun tangguh untuk konter HP outdoor & rugged phone tahan banting.",
    badge: "Tactical Outdoor",
    colors: {
      isDark: true,
      bgMain: "bg-[#0d120f]",
      bgContainer: "bg-[#17211b]",
      borderContainer: "border-[#25362c]",
      textPrimary: "text-[#e4ede7]",
      textSecondary: "text-[#8fa396]",
      accent: "bg-[#3e664d]",
      accentHover: "hover:bg-[#4d7d5f]",
      accentText: "text-[#5cb37b]",
      badgeVerifiedBg: "bg-[#142118]",
      badgeVerifiedText: "text-[#5cb37b]",
      badgeVerifiedBorder: "border-[#2b4533]",
      cardBg: "bg-[#17211b]/80",
      cardBorder: "border-[#25362c]",
      cardHoverBorder: "hover:border-[#5cb37b]/50",
      headerBg: "bg-[#17211b]/90 border-[#25362c] text-[#e4ede7]",
      bottomNavBg: "bg-[#17211b]/95 border-[#25362c]",
      bottomNavBorder: "border-[#25362c]",
      bottomNavActive: "text-[#5cb37b] font-bold",
      bottomNavInactive: "text-[#8fa396] hover:text-[#e4ede7]",
      priceText: "text-[#5cb37b] font-mono",
      heroGradient: "bg-gradient-to-br from-[#1c2e22] via-[#284231] to-[#131f17] text-white",
      heroBorder: "border-[#3e664d]",
    },
  },
  "pastel-matcha": {
    id: "pastel-matcha",
    name: "Pastel Matcha Soft Clean",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Hijau matcha lembut menenangkan, cocok untuk katalog HP warna pastel wanita muda.",
    badge: "Soft Pastel",
    colors: {
      isDark: false,
      bgMain: "bg-[#f2f7f2]",
      bgContainer: "bg-white",
      borderContainer: "border-[#d8e6d8]",
      textPrimary: "text-[#283828]",
      textSecondary: "text-[#627a62]",
      accent: "bg-[#538253]",
      accentHover: "hover:bg-[#436b43]",
      accentText: "text-[#538253]",
      badgeVerifiedBg: "bg-[#e5f0e5]",
      badgeVerifiedText: "text-[#325232]",
      badgeVerifiedBorder: "border-[#c4dec4]",
      cardBg: "bg-white",
      cardBorder: "border-[#d8e6d8]",
      cardHoverBorder: "hover:border-[#538253]/50",
      headerBg: "bg-white/90 border-[#d8e6d8] text-[#283828]",
      bottomNavBg: "bg-white/95 border-[#d8e6d8]",
      bottomNavBorder: "border-[#d8e6d8]",
      bottomNavActive: "text-[#538253] font-bold",
      bottomNavInactive: "text-[#627a62] hover:text-[#283828]",
      priceText: "text-[#538253] font-bold",
      heroGradient: "bg-gradient-to-br from-[#538253] via-[#6a9e6a] to-[#3f633f] text-white",
      heroBorder: "border-[#538253]",
    },
  },
  "sakura-blossom": {
    id: "sakura-blossom",
    name: "Sakura Blossom Pink",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Merah muda bunga sakura feminin dan manis untuk pecinta iPhone pink & casing estetik.",
    badge: "Feminin Chic",
    colors: {
      isDark: false,
      bgMain: "bg-pink-50/60",
      bgContainer: "bg-white",
      borderContainer: "border-pink-200",
      textPrimary: "text-slate-900",
      textSecondary: "text-slate-500",
      accent: "bg-pink-500",
      accentHover: "hover:bg-pink-600",
      accentText: "text-pink-600",
      badgeVerifiedBg: "bg-pink-100",
      badgeVerifiedText: "text-pink-800",
      badgeVerifiedBorder: "border-pink-200",
      cardBg: "bg-white",
      cardBorder: "border-pink-100",
      cardHoverBorder: "hover:border-pink-300",
      headerBg: "bg-white/90 border-pink-200 text-slate-900",
      bottomNavBg: "bg-white/95 border-pink-200",
      bottomNavBorder: "border-pink-200",
      bottomNavActive: "text-pink-600 font-bold",
      bottomNavInactive: "text-slate-400 hover:text-slate-700",
      priceText: "text-pink-600 font-bold",
      heroGradient: "bg-gradient-to-br from-pink-400 via-rose-400 to-pink-600 text-white",
      heroBorder: "border-pink-300",
    },
  },
  "deep-ocean-navy": {
    id: "deep-ocean-navy",
    name: "Deep Ocean Corporate Navy",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Biru laut dalam profesional yang memancarkan kredibilitas tinggi, mirip showroom resmi.",
    badge: "Official Showroom",
    colors: {
      isDark: true,
      bgMain: "bg-[#070e1b]",
      bgContainer: "bg-[#0e1b33]",
      borderContainer: "border-blue-950",
      textPrimary: "text-blue-50",
      textSecondary: "text-blue-300/60",
      accent: "bg-blue-600",
      accentHover: "hover:bg-blue-500",
      accentText: "text-blue-400",
      badgeVerifiedBg: "bg-blue-950",
      badgeVerifiedText: "text-blue-300",
      badgeVerifiedBorder: "border-blue-800/80",
      cardBg: "bg-[#0e1b33]/80",
      cardBorder: "border-blue-950",
      cardHoverBorder: "hover:border-blue-500/50",
      headerBg: "bg-[#0e1b33]/90 border-blue-950 text-blue-50",
      bottomNavBg: "bg-[#0e1b33]/95 border-blue-950",
      bottomNavBorder: "border-blue-950",
      bottomNavActive: "text-blue-400 font-bold",
      bottomNavInactive: "text-blue-400/60 hover:text-blue-200",
      priceText: "text-blue-300 font-mono",
      heroGradient: "bg-gradient-to-br from-[#0e1b33] via-[#14284d] to-[#081224] text-white",
      heroBorder: "border-blue-500/40",
    },
  },
  "charcoal-minimal": {
    id: "charcoal-minimal",
    name: "Charcoal Slate Matte",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Abu-abu arang doff elegan yang tenang dengan sentuhan modern understated luxury.",
    badge: "Matte Charcoal",
    colors: {
      isDark: true,
      bgMain: "bg-[#181a1b]",
      bgContainer: "bg-[#222527]",
      borderContainer: "border-[#313538]",
      textPrimary: "text-[#f0f2f4]",
      textSecondary: "text-[#9ba2a8]",
      accent: "bg-[#3e4448]",
      accentHover: "hover:bg-[#4d5459]",
      accentText: "text-[#cfd4d8]",
      badgeVerifiedBg: "bg-[#1c1f20]",
      badgeVerifiedText: "text-[#cfd4d8]",
      badgeVerifiedBorder: "border-[#3b4044]",
      cardBg: "bg-[#222527]/80",
      cardBorder: "border-[#313538]",
      cardHoverBorder: "hover:border-[#cfd4d8]/40",
      headerBg: "bg-[#222527]/90 border-[#313538] text-[#f0f2f4]",
      bottomNavBg: "bg-[#222527]/95 border-[#313538]",
      bottomNavBorder: "border-[#313538]",
      bottomNavActive: "text-[#cfd4d8] font-bold",
      bottomNavInactive: "text-[#9ba2a8] hover:text-[#f0f2f4]",
      priceText: "text-[#cfd4d8] font-mono",
      heroGradient: "bg-gradient-to-br from-[#222527] via-[#2d3135] to-[#181a1b] text-white",
      heroBorder: "border-[#3e4448]",
    },
  },
  "retro-synthwave": {
    id: "retro-synthwave",
    name: "Retro Synthwave 80s",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Gradasi neon magenta dan cyan khas tahun 80-an yang mencolok dan artistik.",
    badge: "Retro 80s",
    colors: {
      isDark: true,
      bgMain: "bg-[#10061e]",
      bgContainer: "bg-[#1d0d36]",
      borderContainer: "border-fuchsia-900/40",
      textPrimary: "text-fuchsia-50",
      textSecondary: "text-fuchsia-300/60",
      accent: "bg-fuchsia-600",
      accentHover: "hover:bg-fuchsia-500",
      accentText: "text-fuchsia-400",
      badgeVerifiedBg: "bg-fuchsia-950",
      badgeVerifiedText: "text-fuchsia-300",
      badgeVerifiedBorder: "border-fuchsia-700/60",
      cardBg: "bg-[#1d0d36]/80",
      cardBorder: "border-fuchsia-900/30",
      cardHoverBorder: "hover:border-cyan-400/50",
      headerBg: "bg-[#1d0d36]/90 border-fuchsia-950 text-fuchsia-50",
      bottomNavBg: "bg-[#1d0d36]/95 border-fuchsia-950",
      bottomNavBorder: "border-fuchsia-950",
      bottomNavActive: "text-cyan-400 font-bold",
      bottomNavInactive: "text-fuchsia-400/60 hover:text-fuchsia-200",
      priceText: "text-cyan-400 font-mono",
      heroGradient: "bg-gradient-to-br from-[#1d0d36] via-[#3a156e] to-[#0a1b38] text-white",
      heroBorder: "border-fuchsia-500/40",
    },
  },
  "vintage-sepia": {
    id: "vintage-sepia",
    name: "Vintage Sepia Bookish",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Nuansa kertas buku tua & kopi klasik yang hangat dan ramah di mata pembeli.",
    badge: "Warm Vintage",
    colors: {
      isDark: false,
      bgMain: "bg-[#ede7dd]",
      bgContainer: "bg-[#faf7f2]",
      borderContainer: "border-[#d8cebe]",
      textPrimary: "text-[#3b3226]",
      textSecondary: "text-[#7a6f5d]",
      accent: "bg-[#8a6847]",
      accentHover: "hover:bg-[#705235]",
      accentText: "text-[#8a6847]",
      badgeVerifiedBg: "bg-[#eee4d6]",
      badgeVerifiedText: "text-[#5e442c]",
      badgeVerifiedBorder: "border-[#cfbea8]",
      cardBg: "bg-white",
      cardBorder: "border-[#d8cebe]",
      cardHoverBorder: "hover:border-[#8a6847]",
      headerBg: "bg-[#faf7f2]/90 border-[#d8cebe] text-[#3b3226]",
      bottomNavBg: "bg-[#faf7f2]/95 border-[#d8cebe]",
      bottomNavBorder: "border-[#d8cebe]",
      bottomNavActive: "text-[#8a6847] font-bold",
      bottomNavInactive: "text-[#7a6f5d] hover:text-[#3b3226]",
      priceText: "text-[#8a6847] font-bold",
      heroGradient: "bg-gradient-to-br from-[#8a6847] via-[#a8825b] to-[#6d4f33] text-white",
      heroBorder: "border-[#8a6847]",
    },
  },
  "neon-lime-bold": {
    id: "neon-lime-bold",
    name: "Neon Lime Speed Runner",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Aksen hijau limau menyala di atas canvas abu-abu gelap dengan kontras ekstrem.",
    badge: "Neon Lime",
    colors: {
      isDark: true,
      bgMain: "bg-[#0e100f]",
      bgContainer: "bg-[#181c19]",
      borderContainer: "border-[#273029]",
      textPrimary: "text-slate-100",
      textSecondary: "text-slate-400",
      accent: "bg-[#a3e635]",
      accentHover: "hover:bg-[#bef264]",
      accentText: "text-[#a3e635]",
      badgeVerifiedBg: "bg-[#17240c]",
      badgeVerifiedText: "text-[#a3e635]",
      badgeVerifiedBorder: "border-[#2b4217]",
      cardBg: "bg-[#181c19]/80",
      cardBorder: "border-[#273029]",
      cardHoverBorder: "hover:border-[#a3e635]/50",
      headerBg: "bg-[#181c19]/90 border-[#273029] text-white",
      bottomNavBg: "bg-[#181c19]/95 border-[#273029]",
      bottomNavBorder: "border-[#273029]",
      bottomNavActive: "text-[#a3e635] font-bold",
      bottomNavInactive: "text-slate-400 hover:text-slate-200",
      priceText: "text-[#a3e635] font-mono",
      heroGradient: "bg-gradient-to-br from-[#181c19] via-[#242e26] to-[#0e100f] text-white",
      heroBorder: "border-[#a3e635]/40",
    },
  },
  "cappuccino-coffee": {
    id: "cappuccino-coffee",
    name: "Barista Coffee Latte",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Cokelat espresso dan busa susu latte yang bersahabat, nyaman, dan estetik.",
    badge: "Coffee Shop",
    colors: {
      isDark: false,
      bgMain: "bg-[#f5efe8]",
      bgContainer: "bg-[#fffcf9]",
      borderContainer: "border-[#e0d3c5]",
      textPrimary: "text-[#36271c]",
      textSecondary: "text-[#7a6452]",
      accent: "bg-[#694833]",
      accentHover: "hover:bg-[#523724]",
      accentText: "text-[#694833]",
      badgeVerifiedBg: "bg-[#ebdacf]",
      badgeVerifiedText: "text-[#473020]",
      badgeVerifiedBorder: "border-[#d1b8a5]",
      cardBg: "bg-white",
      cardBorder: "border-[#e0d3c5]",
      cardHoverBorder: "hover:border-[#694833]",
      headerBg: "bg-[#fffcf9]/90 border-[#e0d3c5] text-[#36271c]",
      bottomNavBg: "bg-[#fffcf9]/95 border-[#e0d3c5]",
      bottomNavBorder: "border-[#e0d3c5]",
      bottomNavActive: "text-[#694833] font-bold",
      bottomNavInactive: "text-[#7a6452] hover:text-[#36271c]",
      priceText: "text-[#694833] font-bold",
      heroGradient: "bg-gradient-to-br from-[#694833] via-[#855f45] to-[#4d3221] text-white",
      heroBorder: "border-[#694833]",
    },
  },
  "cosmic-starlight": {
    id: "cosmic-starlight",
    name: "Cosmic Starlight Deep Space",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Ruang angkasa dalam bertabur bintang putih perak dengan aksen biru galaksi.",
    badge: "Deep Space",
    colors: {
      isDark: true,
      bgMain: "bg-[#030712]",
      bgContainer: "bg-[#0a1128]",
      borderContainer: "border-[#1e2a4a]",
      textPrimary: "text-slate-100",
      textSecondary: "text-slate-400",
      accent: "bg-sky-500",
      accentHover: "hover:bg-sky-400",
      accentText: "text-sky-400",
      badgeVerifiedBg: "bg-sky-950",
      badgeVerifiedText: "text-sky-300",
      badgeVerifiedBorder: "border-sky-800/80",
      cardBg: "bg-[#0a1128]/80",
      cardBorder: "border-[#1e2a4a]",
      cardHoverBorder: "hover:border-sky-400/50",
      headerBg: "bg-[#0a1128]/90 border-[#1e2a4a] text-white",
      bottomNavBg: "bg-[#0a1128]/95 border-[#1e2a4a]",
      bottomNavBorder: "border-[#1e2a4a]",
      bottomNavActive: "text-sky-400 font-bold",
      bottomNavInactive: "text-slate-400 hover:text-slate-200",
      priceText: "text-sky-400 font-mono",
      heroGradient: "bg-gradient-to-br from-[#0a1128] via-[#12224d] to-[#030712] text-white",
      heroBorder: "border-sky-500/40",
    },
  },
  "royal-ruby": {
    id: "royal-ruby",
    name: "Royal Ruby Red Velvet",
    category: "Advance",
    tierRequired: "ADVANCE",
    description: "Batu rubi kerajaan mewah dengan warna merah tua marun yang berwibawa.",
    badge: "Royal Ruby",
    colors: {
      isDark: true,
      bgMain: "bg-[#140608]",
      bgContainer: "bg-[#220d11]",
      borderContainer: "border-rose-950",
      textPrimary: "text-rose-50",
      textSecondary: "text-rose-300/60",
      accent: "bg-rose-700",
      accentHover: "hover:bg-rose-600",
      accentText: "text-rose-400",
      badgeVerifiedBg: "bg-rose-950",
      badgeVerifiedText: "text-rose-300",
      badgeVerifiedBorder: "border-rose-800/80",
      cardBg: "bg-[#220d11]/80",
      cardBorder: "border-rose-950",
      cardHoverBorder: "hover:border-rose-500/50",
      headerBg: "bg-[#220d11]/90 border-rose-950 text-rose-50",
      bottomNavBg: "bg-[#220d11]/95 border-rose-950",
      bottomNavBorder: "border-rose-950",
      bottomNavActive: "text-rose-400 font-bold",
      bottomNavInactive: "text-rose-400/60 hover:text-rose-200",
      priceText: "text-rose-300 font-mono",
      heroGradient: "bg-gradient-to-br from-[#220d11] via-[#3d141c] to-[#140608] text-white",
      heroBorder: "border-rose-600/40",
    },
  },
};

export const TEMPLATE_LIST = Object.values(TEMPLATE_REGISTRY);

/**
 * Filter template yang tersedia berdasarkan tier langganan toko.
 * - STARTER: 2 template
 * - PRO: 10 template (Starter + Pro)
 * - ADVANCE: 30 template (Semua)
 */
export function getAvailableTemplatesForTier(tier: string | undefined): TemplateThemeConfig[] {
  const cleanTier = (tier || "STARTER").toUpperCase();
  if (cleanTier === "ADVANCE") {
    return TEMPLATE_LIST;
  }
  if (cleanTier === "PRO") {
    return TEMPLATE_LIST.filter((t) => t.tierRequired === "STARTER" || t.tierRequired === "PRO");
  }
  return TEMPLATE_LIST.filter((t) => t.tierRequired === "STARTER");
}

export function getTemplateConfig(templateId: string | undefined): TemplateThemeConfig {
  if (templateId && TEMPLATE_REGISTRY[templateId]) {
    return TEMPLATE_REGISTRY[templateId];
  }
  return TEMPLATE_REGISTRY["minimal-clean"];
}
