const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

async function ensureDemoData() {
  console.log("🌱 Ensuring demo stores and products exist (Upsert Mode)...");

  // 0. Ensure Subscription Plans exist
  const plans = [
    {
      id: "STARTER",
      name: "Starter",
      labelBadge: "STARTER • PERINTIS",
      tagline: "Langkah Awal Konter Manual Jadi Katalog Online",
      price: 250000,
      originalPrice: 350000,
      discountBadge: "HEMAT 28%",
      popularBadge: null,
      period: "/ bulan",
      maxActiveProducts: 15,
      maxAdmins: 1,
      availableTemplatesCount: 2,
      templateCooldownDays: -1,
      templateChangeRule: "Hanya 1x saat pendaftaran",
      hasWatermark: false,
      hasQrWebsite: true,
      hasQrGoogleReview: false,
      hasStoryMaker: false,
      hasCustomDomain: false,
      reportsLevel: "BASIC_WA",
      description: "Solusi hemat untuk toko HP pemula / konter personal yang ingin katalog online rapi.",
    },
    {
      id: "PRO",
      name: "Pro",
      labelBadge: "PRO • BISNIS MANDIRI",
      tagline: "Solusi Lengkap Toko Berkembang: Bebas Curi Foto",
      price: 600000,
      originalPrice: 850000,
      discountBadge: "HEMAT 30%",
      popularBadge: "PALING POPULER",
      period: "/ bulan",
      maxActiveProducts: 30,
      maxAdmins: 3,
      availableTemplatesCount: 4,
      templateCooldownDays: 30,
      templateChangeRule: "Ganti template tiap 30 hari",
      hasWatermark: true,
      hasQrWebsite: true,
      hasQrGoogleReview: true,
      hasStoryMaker: true,
      hasCustomDomain: true,
      reportsLevel: "SOLD_LEADERBOARD",
      description: "Untuk konter HP aktif BEC / Bandung yang ingin scale-up penjualan & branding profesional.",
    },
    {
      id: "ADVANCE",
      name: "Advance",
      labelBadge: "ADVANCE • KELAS SULTAN",
      tagline: "Ekosistem Tanpa Batas untuk Jaringan Cabang",
      price: 1000000,
      originalPrice: 1500000,
      discountBadge: "HEMAT 33%",
      popularBadge: "EKSKLUSIF",
      period: "/ bulan",
      maxActiveProducts: 999999,
      maxAdmins: 5,
      availableTemplatesCount: 6,
      templateCooldownDays: 0,
      templateChangeRule: "Bebas ganti template kapan saja",
      hasWatermark: true,
      hasQrWebsite: true,
      hasQrGoogleReview: true,
      hasStoryMaker: true,
      hasCustomDomain: true,
      reportsLevel: "BRANCH_FULL",
      description: "Kapasitas tanpa batas untuk juragan HP second dengan perputaran stok masif & multi-cabang.",
    },
  ];

  for (const plan of plans) {
    await prisma.subscriptionPlan.upsert({
      where: { id: plan.id },
      update: plan,
      create: plan,
    });
  }

  // 1. Berkah Cell (Minimal-Clean theme, Pro Tier)
  const berkahCell = await prisma.store.upsert({
    where: { slug: "berkahcell" },
    update: {
      name: "Berkah Cell Gadget",
      tier: "PRO",
      planId: "PRO",
      templateId: "minimal-clean",
      whatsapp: "6281234567890",
      address: "Bandung Electronic Center (BEC) Lantai 1 Blok C-05, Jl. Purnawarman No. 13-15, Bandung",
      mapsUrl: "https://maps.google.com/?q=Bandung+Electronic+Center",
      primaryColor: "#2563eb",
      logoUrl: "https://images.unsplash.com/photo-1596558450268-9c27524ba856?w=200&auto=format&fit=crop&q=80",
      bannerUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&auto=format&fit=crop&q=80",
      hasWatermark: true,
      isActive: true,
    },
    create: {
      name: "Berkah Cell Gadget",
      slug: "berkahcell",
      customDomain: null,
      whatsapp: "6281234567890",
      address: "Bandung Electronic Center (BEC) Lantai 1 Blok C-05, Jl. Purnawarman No. 13-15, Bandung",
      mapsUrl: "https://maps.google.com/?q=Bandung+Electronic+Center",
      tier: "PRO",
      planId: "PRO",
      templateId: "minimal-clean",
      primaryColor: "#2563eb",
      logoUrl: "https://images.unsplash.com/photo-1596558450268-9c27524ba856?w=200&auto=format&fit=crop&q=80",
      bannerUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&auto=format&fit=crop&q=80",
      hasWatermark: true,
      lastTemplateChangeAt: new Date(Date.now() - 40 * 24 * 3600 * 1000),
      isActive: true,
    },
  });

  await prisma.product.deleteMany({ where: { storeId: berkahCell.id } });
  await prisma.product.createMany({
    data: [
      {
        storeId: berkahCell.id,
        title: "iPhone 15 Pro Max 256GB Natural Titanium",
        name: "iPhone 15 Pro Max 256GB Natural Titanium",
        slug: "iphone-15-pro-max-256gb-natural-titanium",
        category: "SMARTPHONE",
        brand: "Apple",
        price: 18500000,
        grade: "Grade A+ (Mulus Like New)",
        ram: "8GB",
        storage: "256GB",
        ramRom: "8GB / 256GB",
        batteryHealth: "94% Original",
        completeness: "Fullset Box Original + Kabel C to C",
        conditionNotes: "Fisik istimewa terawat, 3uTools hijau semua, TrueTone & FaceID normal",
        minusNotes: "Fisik istimewa terawat, 3uTools hijau semua, TrueTone & FaceID normal",
        description: "Garansi resmi iBox aktif, bebas blokir IMEI seumur hidup. Free tempered glass & softcase premium.",
        status: "AVAILABLE",
        images: [
          "/images/items/iphone-15-pro.png",
          "/images/items/samsung-s24-ultra.png",
        ],
        imeiStatus: "Resmi iBox (Kemenperin Aman)",
        condition: "Grade A+ (Mulus Like New)",
      },
      {
        storeId: berkahCell.id,
        title: "Samsung Galaxy S24 Ultra 12/512GB Titanium Gray",
        name: "Samsung Galaxy S24 Ultra 12/512GB Titanium Gray",
        slug: "samsung-galaxy-s24-ultra-12-512gb-titanium-gray",
        category: "SMARTPHONE",
        brand: "Samsung",
        price: 15900000,
        grade: "Grade A (99% Mulus)",
        ram: "12GB",
        storage: "512GB",
        ramRom: "12GB / 512GB",
        batteryHealth: "Awet Seharian Normal",
        completeness: "Fullset Original Box + Stylus S-Pen",
        conditionNotes: "Garansi resmi SEIN aktif, layar Dynamic AMOLED mulus bebas shadow",
        minusNotes: "Garansi resmi aktif, layar dynamic AMOLED mulus bebas shadow",
        description: "Galaxy AI aktif permanen. Pemakaian pribadi sangat terawat bebas minus.",
        status: "AVAILABLE",
        images: [
          "/images/items/samsung-s24-ultra.png",
          "/images/items/iphone-15-pro.png",
        ],
        imeiStatus: "Resmi SEIN Indonesia",
        condition: "Grade A (99% Mulus)",
      },
      {
        storeId: berkahCell.id,
        title: "Xiaomi 14T Pro 12/512GB Leica Titan Black",
        name: "Xiaomi 14T Pro 12/512GB Leica Titan Black",
        slug: "xiaomi-14t-pro-12-512gb-leica-titan-black",
        category: "SMARTPHONE",
        brand: "Xiaomi",
        price: 8750000,
        grade: "Grade A+ (Mulus Like New)",
        ram: "12GB",
        storage: "512GB",
        ramRom: "12GB / 512GB",
        batteryHealth: "Baterai 5000mAh Prima",
        completeness: "Fullset Original 120W HyperCharge",
        conditionNotes: "No minus mulus total, Leica Summicron optics super jernih",
        minusNotes: "No minus mulus total, Leica summicron optic super jernih",
        description: "Sensor Leica Summilux flagship. Charger super cepat 120W terisi penuh 19 menit.",
        status: "AVAILABLE",
        images: [
          "/images/items/xiaomi-14t-pro.png",
          "/images/items/rog-phone-8.png",
        ],
        imeiStatus: "Resmi Xiaomi Indonesia",
        condition: "Grade A+ (Mulus Like New)",
      },
      {
        storeId: berkahCell.id,
        title: "ASUS ROG Phone 8 16/256GB Phantom Black",
        name: "ASUS ROG Phone 8 16/256GB Phantom Black",
        slug: "asus-rog-phone-8-16-256gb-phantom-black",
        category: "SMARTPHONE",
        brand: "ASUS ROG",
        price: 10800000,
        grade: "Grade A (97% Terawat)",
        ram: "16GB",
        storage: "256GB",
        ramRom: "16GB / 256GB",
        batteryHealth: "5500mAh Awet Normal",
        completeness: "Fullset Box Original + 65W Charger",
        conditionNotes: "Snapdragon 8 Gen 3 beast gaming, AirTrigger responsif normal",
        minusNotes: "Snapdragon 8 Gen 3 beast gaming, AirTrigger responsif normal",
        description: "Gaming phone terkencang. Layar AMOLED 165Hz ultra-mulus siap kompetisi esports.",
        status: "AVAILABLE",
        images: [
          "/images/items/rog-phone-8.png",
          "/images/items/xiaomi-14t-pro.png",
        ],
        imeiStatus: "Resmi ASUS Indonesia",
        condition: "Grade A (97% Terawat)",
      },
    ],
  });

  // 2. Gamers Gadget (Dark-Gaming theme, Starter Tier)
  const gamersGadget = await prisma.store.upsert({
    where: { slug: "gamersgadget" },
    update: {
      name: "Gamers Gadget Bandung",
      tier: "STARTER",
      planId: "STARTER",
      templateId: "dark-gaming",
      whatsapp: "6289876543210",
      address: "ITC Kebon Kelapa Lantai 3 Blok F No. 8, Jl. Moh. Toha, Bandung",
      mapsUrl: "https://maps.google.com/?q=ITC+Kebon+Kelapa+Bandung",
      primaryColor: "#10b981",
      logoUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=200&auto=format&fit=crop&q=80",
      bannerUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop&q=80",
      hasWatermark: false,
      isActive: true,
    },
    create: {
      name: "Gamers Gadget Bandung",
      slug: "gamersgadget",
      customDomain: null,
      whatsapp: "6289876543210",
      address: "ITC Kebon Kelapa Lantai 3 Blok F No. 8, Jl. Moh. Toha, Bandung",
      mapsUrl: "https://maps.google.com/?q=ITC+Kebon+Kelapa+Bandung",
      tier: "STARTER",
      planId: "STARTER",
      templateId: "dark-gaming",
      primaryColor: "#10b981",
      logoUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=200&auto=format&fit=crop&q=80",
      bannerUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop&q=80",
      hasWatermark: false,
      lastTemplateChangeAt: null,
      isActive: true,
    },
  });

  await prisma.product.deleteMany({ where: { storeId: gamersGadget.id } });
  await prisma.product.createMany({
    data: [
      {
        storeId: gamersGadget.id,
        title: "ASUS ROG Phone 8 16/256GB Phantom Black",
        name: "ASUS ROG Phone 8 16/256GB Phantom Black",
        slug: "asus-rog-phone-8-gamers-gadget",
        category: "SMARTPHONE",
        brand: "ASUS ROG",
        price: 10800000,
        grade: "Grade A+ (Mulus Like New)",
        ram: "16GB",
        storage: "256GB",
        ramRom: "16GB / 256GB",
        batteryHealth: "6000mAh Awet Seharian",
        completeness: "Fullset Box + AeroActive Cooler + 65W HyperCharge",
        conditionNotes: "AirTrigger normal responsif, RGB Matrix nyala normal, baterai super awet",
        minusNotes: "AirTrigger normal responsif, RGB Matrix nyala normal, baterai 6000mAh super awet",
        description: "Paket lengkap dengan Cooler eksternal. Siap push rank tanpa drop FPS.",
        status: "AVAILABLE",
        images: [
          "/images/items/rog-phone-8.png",
          "/images/items/xiaomi-14t-pro.png",
        ],
        imeiStatus: "Resmi ASUS Indonesia",
        condition: "Grade A+ (Mulus Like New)",
      },
      {
        storeId: gamersGadget.id,
        title: "Xiaomi 14T Pro 12/512GB Leica Titan Black",
        name: "Xiaomi 14T Pro 12/512GB Leica Titan Black",
        slug: "xiaomi-14t-pro-gamers-gadget",
        category: "SMARTPHONE",
        brand: "Xiaomi",
        price: 8750000,
        grade: "Grade A+ (Mulus Like New)",
        ram: "12GB",
        storage: "512GB",
        ramRom: "12GB / 512GB",
        batteryHealth: "5000mAh Sehat 100%",
        completeness: "Fullset Original 120W FlashCharge",
        conditionNotes: "Dimensity 9300+ beast gaming, no minus sama sekali, garansi on",
        minusNotes: "Snapdragon 8 Gen 3 beast gaming, no minus sama sekali, garansi on",
        description: "Performa gaming monster dengan lensa Leica. Garansi resmi Xiaomi aktif.",
        status: "AVAILABLE",
        images: [
          "/images/items/xiaomi-14t-pro.png",
          "/images/items/iphone-15-pro.png",
        ],
        imeiStatus: "Resmi Xiaomi Indonesia",
        condition: "Grade A+ (Mulus Like New)",
      },
      {
        storeId: gamersGadget.id,
        title: "iPhone 15 Pro Max 256GB Natural Titanium",
        name: "iPhone 15 Pro Max 256GB Natural Titanium",
        slug: "iphone-15-pro-max-gamers-gadget",
        category: "SMARTPHONE",
        brand: "Apple",
        price: 18500000,
        grade: "Grade A (98% Mulus)",
        ram: "8GB",
        storage: "256GB",
        ramRom: "8GB / 256GB",
        batteryHealth: "94% Original",
        completeness: "Fullset Box Original",
        conditionNotes: "Layar mulus sudah pasang tempered glass matte gaming, no dent",
        minusNotes: "Layar mulus sudah pasang tempered glass matte gaming, no dent",
        description: "Chip A17 Pro lancar main Resident Evil & Assassin's Creed Mirage.",
        status: "AVAILABLE",
        images: [
          "/images/items/iphone-15-pro.png",
          "/images/items/samsung-s24-ultra.png",
        ],
        imeiStatus: "Resmi Digimap (Kemenperin Aktif)",
        condition: "Grade A (98% Mulus)",
      },
      {
        storeId: gamersGadget.id,
        title: "Samsung Galaxy S24 Ultra 12/512GB Titanium Gray",
        name: "Samsung Galaxy S24 Ultra 12/512GB Titanium Gray",
        slug: "samsung-galaxy-s24-ultra-gamers-gadget",
        category: "SMARTPHONE",
        brand: "Samsung",
        price: 15900000,
        grade: "Grade A (98% Mulus)",
        ram: "12GB",
        storage: "512GB",
        ramRom: "12GB / 512GB",
        batteryHealth: "Awet Seharian Normal",
        completeness: "Unit + Stylus S-Pen Original + Box",
        conditionNotes: "Kamera & performa gaming 100% buas bebas minus",
        minusNotes: "Kamera & performa gaming 100% buas bebas minus",
        description: "Vapor chamber lebih besar 1.9x untuk gaming adem marathon.",
        status: "AVAILABLE",
        images: [
          "/images/items/samsung-s24-ultra.png",
          "/images/items/rog-phone-8.png",
        ],
        imeiStatus: "Resmi SEIN Indonesia",
        condition: "Grade A (98% Mulus)",
      },
    ],
  });

  // 3. Tokyo Street Cell (tokyo-editorial / tokyo-street theme, Pro Tier)
  const tokyoStore = await prisma.store.upsert({
    where: { slug: "tokyostreet" },
    update: {
      name: "Tokyo Street Cell",
      tier: "PRO",
      planId: "PRO",
      templateId: "tokyo-editorial",
      whatsapp: "6281234567890",
      address: "Bandung Electronic Center (BEC) Lantai 1 Blok C-08, Jl. Purnawarman No. 13-15, Bandung",
      mapsUrl: "https://maps.google.com/?q=Bandung+Electronic+Center",
      primaryColor: "#e11d48",
      logoUrl: "https://images.unsplash.com/photo-1596558450268-9c27524ba856?w=200&auto=format&fit=crop&q=80",
      bannerUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&auto=format&fit=crop&q=80",
      hasWatermark: true,
      isActive: true,
    },
    create: {
      name: "Tokyo Street Cell",
      slug: "tokyostreet",
      customDomain: null,
      whatsapp: "6281234567890",
      address: "Bandung Electronic Center (BEC) Lantai 1 Blok C-08, Jl. Purnawarman No. 13-15, Bandung",
      mapsUrl: "https://maps.google.com/?q=Bandung+Electronic+Center",
      tier: "PRO",
      planId: "PRO",
      templateId: "tokyo-editorial",
      primaryColor: "#e11d48",
      logoUrl: "https://images.unsplash.com/photo-1596558450268-9c27524ba856?w=200&auto=format&fit=crop&q=80",
      bannerUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&auto=format&fit=crop&q=80",
      hasWatermark: true,
      lastTemplateChangeAt: new Date(Date.now() - 20 * 24 * 3600 * 1000),
      isActive: true,
    },
  });

  await prisma.product.deleteMany({ where: { storeId: tokyoStore.id } });
  await prisma.product.createMany({
    data: [
      {
        storeId: tokyoStore.id,
        title: "iPhone 15 Pro 128GB Black Titanium",
        name: "iPhone 15 Pro 128GB Black Titanium",
        slug: "iphone-15-pro-128gb-black-titanium-tokyo",
        category: "SMARTPHONE",
        brand: "Apple",
        price: 15400000,
        grade: "Grade A+ (Mulus Like New)",
        ram: "8GB",
        storage: "128GB",
        ramRom: "8GB / 128GB",
        batteryHealth: "96% Original",
        completeness: "Fullset Original Box & Kabel",
        conditionNotes: "Fisik istimewa terawat tanpa lecet, 3uTools skor 100",
        minusNotes: "Fisik istimewa terawat tanpa lecet, 3uTools skor 100",
        description: "Unit terpilih Japanese Street style. Sangat elegan dan mulus total.",
        status: "AVAILABLE",
        images: [
          "/images/items/iphone-15-pro.png",
          "/images/items/samsung-s24-ultra.png",
        ],
        imeiStatus: "Resmi iBox Indonesia",
        condition: "Grade A+ (Mulus Like New)",
      },
      {
        storeId: tokyoStore.id,
        title: "Samsung Galaxy S24 Ultra 12/256GB Titanium Black",
        name: "Samsung Galaxy S24 Ultra 12/256GB Titanium Black",
        slug: "samsung-galaxy-s24-ultra-tokyo",
        category: "SMARTPHONE",
        brand: "Samsung",
        price: 15800000,
        grade: "Grade A (98% Mulus)",
        ram: "12GB",
        storage: "256GB",
        ramRom: "12GB / 256GB",
        batteryHealth: "Awet Normal",
        completeness: "Fullset Box Original + Stylus Pen",
        conditionNotes: "Layar & body mulus, Galaxy AI aktif permanen",
        minusNotes: "Layar & body mulus, Galaxy AI aktif permanen",
        description: "Stylus S-Pen responsif presisi. Siap pakai kerja & konten estetik.",
        status: "AVAILABLE",
        images: [
          "/images/items/samsung-s24-ultra.png",
          "/images/items/iphone-15-pro.png",
        ],
        imeiStatus: "Resmi SEIN Indonesia",
        condition: "Grade A (98% Mulus)",
      },
      {
        storeId: tokyoStore.id,
        title: "Xiaomi 14T Pro 12/512GB Titan Black",
        name: "Xiaomi 14T Pro 12/512GB Titan Black",
        slug: "xiaomi-14t-pro-tokyo",
        category: "SMARTPHONE",
        brand: "Xiaomi",
        price: 8400000,
        grade: "Grade A+ (Mulus Like New)",
        ram: "12GB",
        storage: "512GB",
        ramRom: "12GB / 512GB",
        batteryHealth: "100% Kondisi Baru",
        completeness: "Fullset Charger 120W & Box",
        conditionNotes: "Kamera Leica jernih maksimal, pemakaian 2 bulan",
        minusNotes: "Kamera Leica jernih maksimal, pemakaian 2 bulan",
        description: "Street photography champion dengan filter warna Leica Authentic & Vibrant.",
        status: "AVAILABLE",
        images: [
          "/images/items/xiaomi-14t-pro.png",
          "/images/items/rog-phone-8.png",
        ],
        imeiStatus: "Resmi Xiaomi Indonesia",
        condition: "Grade A+ (Mulus Like New)",
      },
      {
        storeId: tokyoStore.id,
        title: "ASUS ROG Phone 8 16/256GB Rebel Grey",
        name: "ASUS ROG Phone 8 16/256GB Rebel Grey",
        slug: "asus-rog-phone-8-tokyo",
        category: "SMARTPHONE",
        brand: "ASUS",
        price: 10200000,
        grade: "Grade A (98% Mulus)",
        ram: "16GB",
        storage: "256GB",
        ramRom: "16GB / 256GB",
        batteryHealth: "Awet Normal 5500mAh",
        completeness: "Fullset Original Box & AeroActive Cooler",
        conditionNotes: "Siap hajar game berat rata kanan 120fps",
        minusNotes: "Siap hajar game berat rata kanan 120fps",
        description: "Warna Rebel Grey langka, tampilan futuristik ala Akihabara.",
        status: "AVAILABLE",
        images: [
          "/images/items/rog-phone-8.png",
          "/images/items/samsung-s24-ultra.png",
        ],
        imeiStatus: "Resmi ASUS Indonesia",
        condition: "Grade A (98% Mulus)",
      },
    ],
  });

  // 4. Cyber Telemetry Cell (cyber-hud theme, Advance Tier)
  const cyberStore = await prisma.store.upsert({
    where: { slug: "cybercell" },
    update: {
      name: "Cyber Telemetry Cell",
      tier: "ADVANCE",
      planId: "ADVANCE",
      templateId: "cyber-hud",
      whatsapp: "6281234567890",
      address: "Bandung Electronic Center (BEC) Lantai 1 Blok C-10, Jl. Purnawarman No. 13-15, Bandung",
      mapsUrl: "https://maps.google.com/?q=Bandung+Electronic+Center",
      primaryColor: "#06b6d4",
      logoUrl: "https://images.unsplash.com/photo-1596558450268-9c27524ba856?w=200&auto=format&fit=crop&q=80",
      bannerUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&auto=format&fit=crop&q=80",
      hasWatermark: true,
      isActive: true,
    },
    create: {
      name: "Cyber Telemetry Cell",
      slug: "cybercell",
      customDomain: null,
      whatsapp: "6281234567890",
      address: "Bandung Electronic Center (BEC) Lantai 1 Blok C-10, Jl. Purnawarman No. 13-15, Bandung",
      mapsUrl: "https://maps.google.com/?q=Bandung+Electronic+Center",
      tier: "ADVANCE",
      planId: "ADVANCE",
      templateId: "cyber-hud",
      primaryColor: "#06b6d4",
      logoUrl: "https://images.unsplash.com/photo-1596558450268-9c27524ba856?w=200&auto=format&fit=crop&q=80",
      bannerUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&auto=format&fit=crop&q=80",
      hasWatermark: true,
      lastTemplateChangeAt: new Date(Date.now() - 10 * 24 * 3600 * 1000),
      isActive: true,
    },
  });

  await prisma.product.deleteMany({ where: { storeId: cyberStore.id } });
  await prisma.product.createMany({
    data: [
      {
        storeId: cyberStore.id,
        title: "ASUS ROG Phone 8 Pro 24GB/1TB Phantom Black",
        name: "ASUS ROG Phone 8 Pro 24GB/1TB Phantom Black",
        slug: "asus-rog-phone-8-pro-cyber",
        category: "SMARTPHONE",
        brand: "ASUS",
        price: 18900000,
        grade: "Grade A+ (Mulus Like New)",
        ram: "24GB",
        storage: "1TB",
        ramRom: "24GB / 1TB",
        batteryHealth: "99% Baterai Monster",
        completeness: "Fullset Box + AeroActive Cooler X + Case",
        conditionNotes: "Benchmark AnTuTu 2.2M, AirTrigger & AniMe Vision aktif 100%",
        minusNotes: "Benchmark AnTuTu 2.2M, AirTrigger & AniMe Vision aktif 100%",
        description: "Spesifikasi puncak RAM 24GB dan Storage 1TB. Display matriks belakang menyala sempurna.",
        status: "AVAILABLE",
        images: [
          "/images/items/rog-phone-8.png",
          "/images/items/xiaomi-14t-pro.png",
        ],
        imeiStatus: "Resmi ASUS Indonesia (Kemenperin Aktif)",
        condition: "Grade A+ (Mulus Like New)",
      },
      {
        storeId: cyberStore.id,
        title: "iPhone 15 Pro Max 256GB Black Titanium",
        name: "iPhone 15 Pro Max 256GB Black Titanium",
        slug: "iphone-15-pro-max-cyber",
        category: "SMARTPHONE",
        brand: "Apple",
        price: 18500000,
        grade: "Grade A (98% Mulus)",
        ram: "8GB",
        storage: "256GB",
        ramRom: "8GB / 256GB",
        batteryHealth: "95% Original",
        completeness: "Fullset Original Box & Braided Cable",
        conditionNotes: "Telemetri 3uTools skor 100 hijau semua, tanpa dent",
        minusNotes: "Telemetri 3uTools skor 100 hijau semua, tanpa dent",
        description: "Bodi titanium kuat dan ringan dengan tombol Action button responsif.",
        status: "AVAILABLE",
        images: [
          "/images/items/iphone-15-pro.png",
          "/images/items/samsung-s24-ultra.png",
        ],
        imeiStatus: "Resmi iBox Indonesia",
        condition: "Grade A (98% Mulus)",
      },
      {
        storeId: cyberStore.id,
        title: "Samsung Galaxy S24 Ultra 12/512GB Titanium Black",
        name: "Samsung Galaxy S24 Ultra 12/512GB Titanium Black",
        slug: "samsung-galaxy-s24-ultra-cyber",
        category: "SMARTPHONE",
        brand: "Samsung",
        price: 16900000,
        grade: "Grade A (98% Mulus)",
        ram: "12GB",
        storage: "512GB",
        ramRom: "12GB / 512GB",
        batteryHealth: "Awet Normal Seharian",
        completeness: "Fullset Box Original + Stylus Pen",
        conditionNotes: "Snapdragon 8 Gen 3 for Galaxy, telemetri kamera 200MP jernih",
        minusNotes: "Snapdragon 8 Gen 3 for Galaxy, telemetri kamera 200MP jernih",
        description: "Layar datar anti-pantulan dengan performa AI real-time terdepan.",
        status: "AVAILABLE",
        images: [
          "/images/items/samsung-s24-ultra.png",
          "/images/items/rog-phone-8.png",
        ],
        imeiStatus: "Resmi SEIN Indonesia",
        condition: "Grade A (98% Mulus)",
      },
      {
        storeId: cyberStore.id,
        title: "Xiaomi 14T Pro 12/512GB Titan Black",
        name: "Xiaomi 14T Pro 12/512GB Titan Black",
        slug: "xiaomi-14t-pro-cyber",
        category: "SMARTPHONE",
        brand: "Xiaomi",
        price: 8400000,
        grade: "Grade A+ (Mulus Like New)",
        ram: "12GB",
        storage: "512GB",
        ramRom: "12GB / 512GB",
        batteryHealth: "5000mAh Kondisi Prima",
        completeness: "Fullset Box + HyperCharge 120W",
        conditionNotes: "Dimensity 9300+ Gaming Monster, sensor kamera Leica Summilux",
        minusNotes: "Dimensity 9300+ Gaming Monster, sensor kamera Leica Summilux",
        description: "Kombinasi chipset flagship dan optik Leica untuk hasil foto telemetri presisi.",
        status: "AVAILABLE",
        images: [
          "/images/items/xiaomi-14t-pro.png",
          "/images/items/iphone-15-pro.png",
        ],
        imeiStatus: "Resmi Xiaomi Indonesia",
        condition: "Grade A+ (Mulus Like New)",
      },
    ],
  });

  // --- STORE 5: MIDNIGHT GOLD LUXURY (goldcell) ---
  const goldStore = await prisma.store.upsert({
    where: { slug: "goldcell" },
    update: {
      name: "Midnight Gold Concierge",
      tier: "ADVANCE",
      planId: "ADVANCE",
      templateId: "midnight-gold",
      whatsapp: "628123456789",
      address: "Bandung Electronic Center (BEC) Lantai LG Blok Z-08, Jl. Purnawarman No. 13-15, Bandung",
      mapsUrl: "https://maps.google.com/?q=Bandung+Electronic+Center",
      primaryColor: "#d4af37",
      logoUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=200&auto=format&fit=crop&q=80",
      bannerUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=80",
      hasWatermark: false,
      operationalHours: "Setiap Hari: 10:00 - 21:00 WIB",
      warrantyPolicy: "Garansi Toko 30 Hari Replace Unit & Jaminan Bebas Blokir IMEI Seumur Hidup.",
      verifiedBadge: true,
      isActive: true,
    },
    create: {
      name: "Midnight Gold Concierge",
      slug: "goldcell",
      customDomain: null,
      whatsapp: "628123456789",
      address: "Bandung Electronic Center (BEC) Lantai LG Blok Z-08, Jl. Purnawarman No. 13-15, Bandung",
      mapsUrl: "https://maps.google.com/?q=Bandung+Electronic+Center",
      tier: "ADVANCE",
      planId: "ADVANCE",
      templateId: "midnight-gold",
      primaryColor: "#d4af37",
      logoUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=200&auto=format&fit=crop&q=80",
      bannerUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=80",
      hasWatermark: false,
      operationalHours: "Setiap Hari: 10:00 - 21:00 WIB",
      warrantyPolicy: "Garansi Toko 30 Hari Replace Unit & Jaminan Bebas Blokir IMEI Seumur Hidup.",
      verifiedBadge: true,
      isActive: true,
    },
  });

  await prisma.product.deleteMany({ where: { storeId: goldStore.id } });
  await prisma.product.createMany({
    data: [
      {
        storeId: goldStore.id,
        title: "iPhone 15 Pro Max 256GB Natural Titanium",
        name: "iPhone 15 Pro Max 256GB Natural Titanium",
        slug: "iphone-15-pro-max-gold",
        category: "SMARTPHONE",
        brand: "Apple",
        price: 18900000,
        grade: "Grade A+ (Mint Condition)",
        ram: "8GB",
        storage: "256GB",
        ramRom: "8GB / 256GB",
        batteryHealth: "96% Original",
        completeness: "Fullset Original Box & Cable Type-C Braided",
        conditionNotes: "Unit mulus tanpa dent, garansi resmi iBox aktif hingga akhir tahun",
        minusNotes: "Unit mulus tanpa dent, garansi resmi iBox aktif hingga akhir tahun",
        description: "Koleksi butik mewah. Pemakaian VIP terawat dengan coating pelindung keramik.",
        status: "AVAILABLE",
        images: [
          "/images/items/iphone-15-pro.png",
          "/images/items/samsung-s24-ultra.png",
        ],
        imeiStatus: "Resmi iBox Kemenperin",
        condition: "Grade A+ (Mint Condition)",
      },
      {
        storeId: goldStore.id,
        title: "Samsung Galaxy S24 Ultra 12/512GB Titanium Gray",
        name: "Samsung Galaxy S24 Ultra 12/512GB Titanium Gray",
        slug: "samsung-galaxy-s24-ultra-gold",
        category: "SMARTPHONE",
        brand: "Samsung",
        price: 17200000,
        grade: "Grade A+ (Seperti Baru)",
        ram: "12GB",
        storage: "512GB",
        ramRom: "12GB / 512GB",
        batteryHealth: "Awet Seharian Normal",
        completeness: "Fullset Box Original + S-Pen + Fast Charger",
        conditionNotes: "Titanium frame bersih mengkilap, layar anti-reflective tanpa gores",
        minusNotes: "Titanium frame bersih mengkilap, layar anti-reflective tanpa gores",
        description: "Lengkap dengan charger 45W Samsung Original dan case kulit premium.",
        status: "AVAILABLE",
        images: [
          "/images/items/samsung-s24-ultra.png",
          "/images/items/iphone-15-pro.png",
        ],
        imeiStatus: "Resmi SEIN Indonesia",
        condition: "Grade A+ (Seperti Baru)",
      },
      {
        storeId: goldStore.id,
        title: "iPhone 14 Pro 128GB Space Black",
        name: "iPhone 14 Pro 128GB Space Black",
        slug: "iphone-14-pro-gold",
        category: "SMARTPHONE",
        brand: "Apple",
        price: 13500000,
        grade: "Grade A (98% Mulus)",
        ram: "6GB",
        storage: "128GB",
        ramRom: "6GB / 128GB",
        batteryHealth: "91% Original",
        completeness: "Fullset Box Original + Cable Lightning",
        conditionNotes: "Stainless steel bezel kinclong, kamera dan True Tone 100% normal",
        minusNotes: "Stainless steel bezel kinclong, kamera dan True Tone 100% normal",
        description: "Dynamic Island interaktif dengan finishing stainless steel premium khas edisi Pro.",
        status: "AVAILABLE",
        images: [
          "/images/items/iphone-15-pro.png",
          "/images/items/xiaomi-14t-pro.png",
        ],
        imeiStatus: "Resmi Digimap Kemenperin",
        condition: "Grade A (98% Mulus)",
      },
      {
        storeId: goldStore.id,
        title: "Samsung Galaxy Z Fold 5 12/512GB Phantom Black",
        name: "Samsung Galaxy Z Fold 5 12/512GB Phantom Black",
        slug: "samsung-galaxy-z-fold-5-gold",
        category: "SMARTPHONE",
        brand: "Samsung",
        price: 15800000,
        grade: "Grade A (98% Mulus Terawat)",
        ram: "12GB",
        storage: "512GB",
        ramRom: "12GB / 512GB",
        batteryHealth: "Awet Normal Seharian",
        completeness: "Fullset Box Original",
        conditionNotes: "Lipatan layar dalam mulus kencang, engsel zero-gap presisi",
        minusNotes: "Lipatan layar dalam mulus kencang, engsel zero-gap presisi",
        description: "Inovasi lipat premium untuk produktivitas multitasking kelas eksekutif.",
        status: "AVAILABLE",
        images: [
          "/images/items/samsung-s24-ultra.png",
          "/images/items/rog-phone-8.png",
        ],
        imeiStatus: "Resmi SEIN Indonesia",
        condition: "Grade A (98% Mulus Terawat)",
      },
    ],
  });

  // Seed sample verified reviews for goldStore if empty
  const reviewCount = await prisma.storeReview.count({ where: { storeId: goldStore.id } });
  if (reviewCount === 0) {
    await prisma.storeReview.createMany({
      data: [
        {
          storeId: goldStore.id,
          customerName: "Calvin Hartono",
          rating: 5,
          comment: "Pelayanan butik sangat eksklusif. Unit iPhone 15 Pro Max kondisi 99% seperti baru, baterai awet dan IMEI resmi terdaftar aktif di iBox.",
          purchasedUnit: "iPhone 15 Pro Max 256GB Natural Titanium",
          isApproved: true,
        },
        {
          storeId: goldStore.id,
          customerName: "Dr. Hendra Wijaya",
          rating: 5,
          comment: "Transaksi COD langsung di BEC sangat memuaskan. Toko menyediakan free migrasi data dan pasang temper glass kualitas premium.",
          purchasedUnit: "Samsung Galaxy S24 Ultra 512GB",
          isApproved: true,
        },
      ],
    });
  }

  console.log("✅ Demo stores and products are guaranteed to exist with full multi-images and specs!");
}

if (require.main === module) {
  ensureDemoData()
    .catch((err) => {
      console.error("Demo data ensure error:", err);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}

module.exports = { ensureDemoData };
